# Generated by Django 3.1.5 on 2022-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('opis', models.CharField(blank=True, max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
