# Generated by Django 3.1.5 on 2022-03-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_todo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
