# Generated by Django 3.1.5 on 2022-03-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
