# Generated by Django 3.1.5 on 2022-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_auto_20220323_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='motyw',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
