# Generated by Django 3.1.5 on 2022-03-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0007_todo_motyw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='motyw',
        ),
    ]
