# Generated by Django 3.1.5 on 2022-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0008_remove_todo_motyw'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='motyw',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
